# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [31]:
import numpy as numpy

#### 2. Print the numpy version and the configuration (★☆☆)

In [32]:
print(numpy.__version__)
numpy.show_config()

1.22.3
blas_info:
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\lib']
    include_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\include']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\lib']
    include_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\include']
    language = f77
lapack_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas']
    library_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\lib']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
    library_dirs = ['E:/Miniconda/envs/IAD_Lab2\\Library\\lib']
    language = f77
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
   

#### 3. Create a null vector of size 10 (★☆☆)

In [33]:
print(numpy.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [34]:
array = numpy.zeros((10,10))
print("%d bytes" % (array.size * array.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [35]:
help(numpy.info(numpy.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
vector = numpy.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
vector = numpy.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [38]:
vector = numpy.arange(50)
vector = vector[::-1]
print(vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [39]:
vector = numpy.arange(9).reshape(3, 3)
print(vector)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [40]:
indices = numpy.nonzero([1,2,0,0,4,0])
print(indices)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
matrix = numpy.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [42]:
matrix = numpy.random.random((3,3,3))
print(matrix)

[[[0.40045212 0.73228267 0.3307214 ]
  [0.42451394 0.79318189 0.93549762]
  [0.39525531 0.93834537 0.17798677]]

 [[0.72030427 0.78575417 0.51654352]
  [0.53540386 0.21766523 0.90783369]
  [0.32406405 0.06787559 0.72885875]]

 [[0.5961081  0.2782641  0.21987008]
  [0.96734437 0.09699151 0.32916675]
  [0.0200847  0.04044772 0.42438995]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:
array = numpy.random.random((10,10))
arrayMin, arrayMax = array.min(), array.max()
print(arrayMin, arrayMax)

0.010352058343524151 0.9835124965963896


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [44]:
vector = numpy.random.random(30)
meanValue = vector.mean()
print(meanValue)

0.4912595333458375


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [45]:
array =  numpy.ones((10,10))
array[1:-1,1:-1] = 0
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [46]:
array = numpy.ones((5,5))
array = numpy.pad(array, pad_width=1, mode='constant', constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [47]:
print(0 * numpy.nan)
print(numpy.nan == numpy.nan)
print(numpy.inf > numpy.nan)
print(numpy.nan - numpy.nan)
print(numpy.nan in set([numpy.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [48]:
matrix = numpy.diag(1+numpy.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [49]:
matrix = numpy.zeros((8,8), dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [50]:
print(numpy.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [51]:
matrix = numpy.tile(numpy.array([[0,1],[1,0]]), (4,4))
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [52]:
matrix  = numpy.random.random((5,5))
matrix = (matrix - numpy.mean (matrix)) / (numpy.std (matrix))
print(matrix)

[[-1.49062688  0.23091323  1.89338194 -0.90777498  0.22034987]
 [-1.07299192  1.33804161  0.88200904  0.53786351 -0.78372078]
 [ 0.25909451 -0.89405926 -1.02624836  0.65414783 -0.51725807]
 [ 0.18554772 -1.06489474 -0.54655899  0.09469501  1.20363381]
 [ 1.18715437  1.83864015 -1.45335624 -1.05742559  0.28944317]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [53]:
color = numpy.dtype([("r", numpy.ubyte),
                  ("g", numpy.ubyte),
                  ("b", numpy.ubyte),
                  ("a", numpy.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [54]:
matrix = numpy.dot(numpy.ones((5,3)), numpy.ones((3,2)))
print(matrix)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [55]:
array = numpy.arange(11)
array[(3 < array) & (array < 8)] *= -1
print(array)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [56]:
#print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [57]:
numpy.array(0) / numpy.array(0)
numpy.array(0) // numpy.array(0)
numpy.array([numpy.nan]).astype(int).astype(float)

C:\Users\retyu\AppData\Local\Temp\ipykernel_12716\1160567314.py:1: RuntimeWarning: invalid value encountered in true_divide
  numpy.array(0) / numpy.array(0)
C:\Users\retyu\AppData\Local\Temp\ipykernel_12716\1160567314.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  numpy.array(0) // numpy.array(0)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [58]:
array = numpy.random.uniform(-10,+10,10)
print(numpy.copysign(numpy.ceil(numpy.abs(array)), array))

[10. 10.  3. -3. -8.  4. -8. -9. -9.  1.]


#### 30. How to find common values between two arrays? (★☆☆)

In [59]:
array1 = numpy.random.randint(0,10,10)
array2 = numpy.random.randint(0,10,10)
print(numpy.intersect1d(array1,array2))

[1 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [60]:
defaults = numpy.seterr(all="ignore")
array = numpy.ones(1) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [61]:
numpy.sqrt(-1) == numpy.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [62]:
yesterday = numpy.datetime64('today') - numpy.timedelta64(1)
today     = numpy.datetime64('today')
tomorrow  = numpy.datetime64('today') + numpy.timedelta64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [63]:
dates = numpy.arange('2022-07', '2022-08', dtype='datetime64[D]')
print(dates)

['2022-07-01' '2022-07-02' '2022-07-03' '2022-07-04' '2022-07-05'
 '2022-07-06' '2022-07-07' '2022-07-08' '2022-07-09' '2022-07-10'
 '2022-07-11' '2022-07-12' '2022-07-13' '2022-07-14' '2022-07-15'
 '2022-07-16' '2022-07-17' '2022-07-18' '2022-07-19' '2022-07-20'
 '2022-07-21' '2022-07-22' '2022-07-23' '2022-07-24' '2022-07-25'
 '2022-07-26' '2022-07-27' '2022-07-28' '2022-07-29' '2022-07-30'
 '2022-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [64]:
A = numpy.ones(3)*1
B = numpy.ones(3)*2
numpy.add(A,B,out=B)
numpy.divide(A,2,out=A)
numpy.negative(A,out=A)
numpy.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [65]:
array = numpy.random.uniform(0,10,10)

print(array - array%1)
print(array // 1)
print(numpy.floor(array))
print(array.astype(int))
print(numpy.trunc(array))

[2. 6. 6. 4. 9. 3. 3. 8. 3. 2.]
[2. 6. 6. 4. 9. 3. 3. 8. 3. 2.]
[2. 6. 6. 4. 9. 3. 3. 8. 3. 2.]
[2 6 6 4 9 3 3 8 3 2]
[2. 6. 6. 4. 9. 3. 3. 8. 3. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [66]:
matrix = numpy.zeros((5,5))
matrix += numpy.arange(5)
print(matrix)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [67]:
def generate():
    for x in range(10):
        yield x
array = numpy.fromiter(generate(),dtype=float,count=-1)
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [68]:
vector = numpy.linspace(0,1,11,endpoint=False)[1:]
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [69]:
vector = numpy.random.random(10)
vector.sort()
print(vector)

[0.50191591 0.55920674 0.56633767 0.67040653 0.77567561 0.81432385
 0.83703954 0.83777209 0.96687895 0.99704163]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [70]:
array = numpy.arange(10)
numpy.add.reduce(array)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [71]:
A = numpy.random.randint(0,2,5)
B = numpy.random.randint(0,2,5)
equal = numpy.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆)

In [72]:
array = numpy.zeros(10)
array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [73]:
matrix = numpy.random.random((10,2))
X,Y = matrix[:,0], matrix[:,1]
R = numpy.sqrt(X**2+Y**2)
T =numpy.arctan(Y,X)
print(R)
print(T)

[0.68871033 0.3618913  0.43318626 0.40832728 0.92242266 0.20681063
 1.20652951 0.59591389 0.19261976 1.24254258]
[0.60288781 0.34714736 0.08971647 0.20073145 0.44326628 0.19072233
 0.63900319 0.43569993 0.1617692  0.74673276]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [74]:
vector = numpy.random.random(10)
vector[vector.argmax()] = 0
print(vector)

[0.27029714 0.56629407 0.10660874 0.         0.38902743 0.337888
 0.18494883 0.19472301 0.0585213  0.41767308]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [75]:
array = numpy.zeros((5,5), [('x',float),('y',float)])
array['x'], array['y'] = numpy.meshgrid(numpy.linspace(0,1,5),numpy.linspace(0,1,5))
print(array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [76]:
X = numpy.arange(8)
Y = X + 0.5
C = 1.0 / numpy.subtract.outer(X, Y)
print(numpy.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [77]:
for type in [numpy.int8, numpy.int32, numpy.int64]:
   print(numpy.iinfo(type).min)
   print(numpy.iinfo(type).max)
for type in [numpy.float32, numpy.float64]:
   print(numpy.finfo(type).min)
   print(numpy.finfo(type).max)
   print(numpy.finfo(type).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [78]:
numpy.set_printoptions(threshold=float("inf"))
array = numpy.zeros((40,40))
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [79]:
vector = numpy.arange(100)
value = numpy.random.uniform(0,100)
index = (numpy.abs(vector-value)).argmin()
print(vector[index])

25


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [80]:
array = numpy.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(array)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\retyu\AppData\Local\Temp\ipykernel_12716\204134258.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  array = numpy.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [81]:
vector = numpy.random.random((10,2))
X,Y = numpy.atleast_2d(vector[:,0], vector[:,1])
D = numpy.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.47162885 0.55639971 0.54417766 1.04580991 0.94032572
  0.87191643 0.81188644 0.66516705 0.9126191 ]
 [0.47162885 0.         0.58099669 0.13946434 0.76507226 0.63447776
  0.94399402 0.40640344 0.68800183 0.46841654]
 [0.55639971 0.58099669 0.         0.5061791  0.59816382 0.54308392
  0.36632306 0.5992499  0.11665818 0.74273556]
 [0.54417766 0.13946434 0.5061791  0.         0.62563438 0.49506039
  0.85642911 0.2803769  0.60227019 0.36846297]
 [1.04580991 0.76507226 0.59816382 0.62563438 0.         0.1336143
  0.6972969  0.41588708 0.57587575 0.49700335]
 [0.94032572 0.63447776 0.54308392 0.49506039 0.1336143  0.
  0.71309368 0.28533351 0.54685625 0.38038133]
 [0.87191643 0.94399402 0.36632306 0.85642911 0.6972969  0.71309368
  0.         0.88026733 0.25605427 1.02134507]
 [0.81188644 0.40640344 0.5992499  0.2803769  0.41588708 0.28533351
  0.88026733 0.         0.65557044 0.14410743]
 [0.66516705 0.68800183 0.11665818 0.60227019 0.57587575 0.54685625
  0.25605427 0.655570

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [82]:
array = (numpy.random.rand(10)*100).astype(numpy.float32)
array2 = array.view(numpy.int32)
array2[:] = array
print(array2)

[30 22  1  9 94 28 10 86  2 31]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [83]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
print(numpy.genfromtxt(s, delimiter=",", dtype=numpy.int))

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\retyu\AppData\Local\Temp\ipykernel_12716\2390217714.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.genfromtxt(s, delimiter=",", dtype=numpy.int))


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [84]:
array = numpy.arange(9).reshape(3,3)
for index, value in numpy.ndenumerate(array):
    print(index, value)
for index in numpy.ndindex(array.shape):
    print(index, array[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [85]:
X, Y = numpy.meshgrid(numpy.linspace(-1,1,10), numpy.linspace(-1,1,10))
D = numpy.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = numpy.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [86]:
n = 10
p = 3
array = numpy.zeros((n,n))
numpy.put(array, numpy.random.choice(range(n*n), p, replace=False),1)
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [87]:
array1 = numpy.random.rand(5, 10)
array2 = array1 - array1.mean(axis=1, keepdims=True)
print(array2)

[[ 0.24947451 -0.05786409 -0.07512624  0.14938216  0.13321943 -0.14043087
  -0.09123671 -0.09298095 -0.30934191  0.23490466]
 [ 0.05306689  0.15733894 -0.08084907  0.18096732 -0.18901595 -0.23922642
   0.34003189 -0.11048329 -0.02166933 -0.09016098]
 [ 0.06950719  0.33767445 -0.26242104 -0.324988   -0.07580557 -0.03689771
   0.00386715 -0.22884627  0.40324858  0.11466122]
 [ 0.06531717 -0.38509222 -0.07597153 -0.28420353  0.5539977   0.09639131
   0.05225631  0.06844445  0.21311375 -0.30425341]
 [ 0.13458732 -0.3147797   0.01615654  0.3360563   0.05858912 -0.20390363
   0.04583707 -0.2943177   0.57925166 -0.35747697]]


#### 59. How to sort an array by the nth column? (★★☆)

In [88]:
array = numpy.random.randint(0,10,(3,3))
print(array)
print(array[array[:,1].argsort()])

[[6 4 7]
 [9 7 8]
 [3 3 2]]
[[3 3 2]
 [6 4 7]
 [9 7 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [89]:
array = numpy.random.randint(0,3,(3,10))
print((~array.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [90]:
array = numpy.random.uniform(0,1,10)
x = 0.5
print(array.flat[numpy.abs(array - x).argmin()])

0.5287585111639904


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [91]:
A = numpy.arange(3).reshape(3,1)
B = numpy.arange(3).reshape(1,3)
it = numpy.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [92]:
class NamedArray(numpy.ndarray):
    def __new__(cls, array, name="no name"):
        obj = numpy.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

print (NamedArray(numpy.arange(10), "range_10").name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [93]:
vector = numpy.ones(10)
vector2 = numpy.random.randint(0,len(vector),20)
numpy.add.at(vector, vector2, 1)
print(vector)

[5. 2. 4. 2. 2. 4. 2. 5. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [94]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = numpy.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [95]:
w, h = 256, 256
I = numpy.random.randint(0, 4, (h, w, 3)).astype(numpy.ubyte)
colors = numpy.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [96]:
A = numpy.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)


[[61 57 59 57]
 [59 42 58 61]
 [68 43 44 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [97]:
D = numpy.random.uniform(0,1,100)
S = numpy.random.randint(0,10,100)
D_sums = numpy.bincount(S, weights=D)
D_counts = numpy.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.6267071  0.57218464 0.50521584 0.69221656 0.45973521 0.6259198
 0.48524517 0.50810343 0.51313303 0.51612598]


#### 69. How to get the diagonal of a dot product? (★★★)

In [98]:
A = numpy.random.uniform(0,1,(5,5))
B = numpy.random.uniform(0,1,(5,5))
numpy.diag(numpy.dot(A, B))

array([0.71535871, 0.43563164, 0.43018862, 2.31257932, 0.4599542 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [99]:
array = numpy.array([1,2,3,4,5])
newArray = 3
array0 = numpy.zeros(len(array) + (len(array)-1)*(newArray))
array0[::newArray+1] = array
print(array0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [100]:
A = numpy.ones((5,5,3))
B = numpy.ones((5,5))
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★)

In [101]:
A = numpy.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [102]:
faces = numpy.random.randint(0,100,(10,3))
F = numpy.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = numpy.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = numpy.unique(G)
print(G)

[( 2, 16) ( 2, 41) ( 5, 77) ( 5, 93) (13, 15) (13, 30) (15, 30) (15, 73)
 (15, 95) (16, 41) (17, 85) (17, 86) (21, 68) (21, 91) (25, 55) (25, 70)
 (35, 43) (35, 59) (35, 71) (35, 88) (43, 61) (43, 71) (43, 92) (55, 70)
 (59, 88) (61, 92) (68, 91) (73, 95) (77, 93) (85, 86)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [103]:
C = numpy.bincount([1,1,2,3,4,4,6])
A = numpy.repeat(numpy.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [104]:
def moving_average(a, n=3) :
    ret = numpy.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
array = numpy.arange(20)
print(moving_average(array, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [4]:
from numpy.lib.stride_tricks import sliding_window_view
array = numpy.arange(10)
print(sliding_window_view(array, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [5]:
array = numpy.random.randint(0,2,100)
numpy.logical_not(array, out=array)

array = numpy.random.uniform(-1.0,1.0,100)
numpy.negative(array, out=array)

array([-0.03728221, -0.44262721,  0.04945664, -0.80497505, -0.05530446,
       -0.71857905,  0.99280108,  0.20741465, -0.69645028, -0.94740076,
       -0.95485492, -0.64304903, -0.17966265,  0.96421803, -0.75726214,
       -0.7626661 , -0.2059044 ,  0.31754238, -0.08359025,  0.22316137,
       -0.01465129,  0.63656396, -0.58072644, -0.37669271, -0.86227043,
        0.59417399,  0.12405931, -0.4967638 , -0.80381303, -0.11657141,
        0.36343954,  0.75731665, -0.19335955, -0.98529671, -0.3407118 ,
       -0.46430409, -0.03043238,  0.26335359,  0.30903136, -0.44687996,
        0.45414249, -0.64632734,  0.17629829,  0.09944917, -0.22285218,
       -0.44151001, -0.56435985, -0.76956028, -0.92535083,  0.05036485,
       -0.32455488,  0.75539277,  0.08911312,  0.99657442, -0.90646156,
       -0.96066492, -0.91263476,  0.42077476,  0.60185527,  0.28936949,
        0.06793953, -0.21895812, -0.94356334,  0.48941104, -0.57089251,
       -0.86541349, -0.99984341, -0.49849871,  0.43197813,  0.82

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [6]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return numpy.sqrt((D**2).sum(axis=1))

P0 = numpy.random.uniform(-10,10,(10,2))
P1 = numpy.random.uniform(-10,10,(10,2))
p  = numpy.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.43010671  3.03491351  9.31458955  6.80543163  3.34572578  9.59824286
 11.4828571   7.98726446  7.27418148  8.33568663]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [7]:
P0 = numpy.random.uniform(-10, 10, (10,2))
P1 = numpy.random.uniform(-10,10,(10,2))
p = numpy.random.uniform(-10, 10, (10,2))
print(numpy.array([distance(P0,P1,p_i) for p_i in p]))

[[3.97163689e+00 5.34496167e+00 7.36205769e+00 6.50369053e+00
  6.76722110e+00 1.31254121e+01 6.45397782e+00 9.76815666e-02
  1.03054450e+01 3.32334221e+00]
 [4.76681806e+00 6.84018129e+00 4.18430499e+00 4.90787738e+00
  6.47100742e-01 1.38970423e+00 2.78038511e+00 2.56418864e+00
  1.37144630e+00 6.59275015e+00]
 [4.29477863e+00 1.14149909e+01 6.91640679e+00 1.26200500e+00
  6.59028175e+00 4.73165606e+00 3.99284811e+00 9.06548944e+00
  4.34184914e+00 7.22851398e+00]
 [1.04769517e+01 5.65689115e+00 1.03406045e+01 2.77999710e+00
  1.34426591e+00 1.05547204e+01 2.48069589e+00 9.04351595e+00
  1.29704835e+01 8.74458003e+00]
 [8.73541470e+00 5.98852824e+00 5.33320503e+00 1.18170792e+01
  7.10240751e+00 4.30301237e+00 9.61915015e+00 4.33554113e+00
  2.28023725e+00 9.66676031e+00]
 [2.83892046e+00 1.28502727e+00 4.27471875e+00 3.33146748e+00
  2.38670230e+00 8.40218251e+00 2.67323652e+00 3.39711585e+00
  7.08489025e+00 1.48272672e+00]
 [4.65108760e+00 3.43225479e+00 2.02364065e+00 4.99804866e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [8]:
from numpy.lib.stride_tricks import sliding_window_view
array = numpy.arange(1, 15, dtype=numpy.uint32)
print(sliding_window_view(array , window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [9]:
array = numpy.random.uniform(0,1,(10,10))
rank = numpy.linalg.matrix_rank(array)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [10]:
array = numpy.random.randint(0,10,50)
print(numpy.bincount(array).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [11]:
array = numpy.random.randint(0,5,(10,10))
print(sliding_window_view(array, window_shape=(3, 3)))

[[[[1 2 4]
   [3 1 4]
   [4 1 1]]

  [[2 4 0]
   [1 4 1]
   [1 1 3]]

  [[4 0 0]
   [4 1 4]
   [1 3 2]]

  [[0 0 1]
   [1 4 1]
   [3 2 1]]

  [[0 1 0]
   [4 1 3]
   [2 1 2]]

  [[1 0 1]
   [1 3 3]
   [1 2 2]]

  [[0 1 3]
   [3 3 4]
   [2 2 3]]

  [[1 3 2]
   [3 4 2]
   [2 3 0]]]


 [[[3 1 4]
   [4 1 1]
   [1 0 1]]

  [[1 4 1]
   [1 1 3]
   [0 1 2]]

  [[4 1 4]
   [1 3 2]
   [1 2 3]]

  [[1 4 1]
   [3 2 1]
   [2 3 2]]

  [[4 1 3]
   [2 1 2]
   [3 2 2]]

  [[1 3 3]
   [1 2 2]
   [2 2 4]]

  [[3 3 4]
   [2 2 3]
   [2 4 0]]

  [[3 4 2]
   [2 3 0]
   [4 0 1]]]


 [[[4 1 1]
   [1 0 1]
   [1 1 4]]

  [[1 1 3]
   [0 1 2]
   [1 4 3]]

  [[1 3 2]
   [1 2 3]
   [4 3 3]]

  [[3 2 1]
   [2 3 2]
   [3 3 4]]

  [[2 1 2]
   [3 2 2]
   [3 4 3]]

  [[1 2 2]
   [2 2 4]
   [4 3 1]]

  [[2 2 3]
   [2 4 0]
   [3 1 0]]

  [[2 3 0]
   [4 0 1]
   [1 0 4]]]


 [[[1 0 1]
   [1 1 4]
   [1 2 1]]

  [[0 1 2]
   [1 4 3]
   [2 1 1]]

  [[1 2 3]
   [4 3 3]
   [1 1 0]]

  [[2 3 2]
   [3 3 4]
   [1 0 0]]

  [[3 2 2]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [12]:
class Symetric(numpy.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(array):
    return numpy.asarray(array + array.T - numpy.diag(array.diagonal())).view(Symetric)

S = symetric(numpy.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 3  7  5  3  9]
 [ 7  7  1 12  4]
 [ 5  1  9 42 14]
 [ 3 12 42  8  8]
 [ 9  4 14  8  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [13]:
p, n = 10, 20
M = numpy.ones((p,n,n))
V = numpy.ones((p,n,1))
S = numpy.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [14]:
array = numpy.ones((16, 16))
k = 4
print(sliding_window_view(array, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [15]:
def iterate(array):

    N = (array[0:-2,0:-2] + array[0:-2,1:-1] + array[0:-2,2:] +
         array[1:-1,0:-2] + array[1:-1,2:] +
         array[2:  ,0:-2] + array[2:  ,1:-1] + array[2:  ,2:])

    birth = (N==3) & (array[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (array[1:-1,1:-1]==1)
    array[...] = 0
    array[1:-1,1:-1][birth | survive] = 1
    return array

array = numpy.random.randint(0,2,(50,50))
for i in range(100): array = iterate(array)
print(array)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [16]:
array = numpy.arange(10000)
numpy.random.shuffle(array)
n = 5
print (array[numpy.argsort(array)[-n:]])

[9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

In [17]:
array = numpy.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = numpy.core.records.fromarrays(array.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [18]:
x = numpy.random.rand(int(5e7))

print(numpy.power(x,3))
print(x*x*x)
print(numpy.einsum('i,i,i->i',x,x,x))

[7.95981432e-06 2.45269764e-01 4.58112714e-02 ... 2.17225580e-01
 9.07817992e-03 3.80973242e-01]
[7.95981432e-06 2.45269764e-01 4.58112714e-02 ... 2.17225580e-01
 9.07817992e-03 3.80973242e-01]
[7.95981432e-06 2.45269764e-01 4.58112714e-02 ... 2.17225580e-01
 9.07817992e-03 3.80973242e-01]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [19]:
A = numpy.random.randint(0,5,(8,3))
B = numpy.random.randint(0,5,(2,2))

C = (A[..., numpy.newaxis, numpy.newaxis] == B)
rows = numpy.where(C.any((3,1)).all(1))[0]
print(rows)

[1 3 4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [20]:
array = numpy.random.randint(0,5,(10,3))
array2 = array[array.max(axis=1) != array.min(axis=1),:]
print(array2)

[[3 1 3]
 [2 3 0]
 [0 1 1]
 [0 2 1]
 [2 4 3]
 [3 1 0]
 [1 0 1]
 [2 1 4]
 [0 1 2]
 [2 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [22]:
I = numpy.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=numpy.uint8)
print(numpy.unpackbits(I[:, numpy.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [24]:
array = numpy.random.randint(0,2,(6,3))
arrayUnique = numpy.unique(array, axis=0)
print(arrayUnique )

[[0 0 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [25]:
A = numpy.random.uniform(0,1,10)
B = numpy.random.uniform(0,1,10)

numpy.einsum('i->', A)       # np.sum(A)
numpy.einsum('i,i->i', A, B) # A * B
numpy.einsum('i,i', A, B)    # np.inner(A, B)
numpy.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.10902069, 0.16303024, 0.1871491 , 0.12833895, 0.15537691,
        0.0920878 , 0.01834581, 0.0109005 , 0.18015414, 0.12032588],
       [0.29783807, 0.44538899, 0.51128028, 0.35061444, 0.42448054,
        0.25157843, 0.05011966, 0.02977951, 0.49217046, 0.32872318],
       [0.34527865, 0.51633195, 0.59271862, 0.40646141, 0.49209313,
        0.29165063, 0.05810288, 0.03452289, 0.57056491, 0.38108324],
       [0.29647179, 0.44334585, 0.50893488, 0.34900606, 0.42253331,
        0.25042436, 0.04988975, 0.02964291, 0.48991272, 0.32721523],
       [0.32166675, 0.48102255, 0.55218551, 0.37866551, 0.45844131,
        0.27170608, 0.05412951, 0.03216204, 0.53154679, 0.35502284],
       [0.12270711, 0.18349701, 0.21064374, 0.14445059, 0.17488288,
        0.10364847, 0.02064893, 0.01226894, 0.20277063, 0.13543155],
       [0.0675279 , 0.10098167, 0.115921  , 0.07949373, 0.09624116,
        0.0570396 , 0.01136348, 0.00675182, 0.11158828, 0.07453039],
       [0.22636659, 0.33851007, 0.3885895

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [28]:
phi = numpy.arange(0, 10*numpy.pi, 0.1)
a = 1
x = a*phi*numpy.cos(phi)
y = a*phi*numpy.sin(phi)

dr = (numpy.diff(x)**2 + numpy.diff(y)**2)**.5 # segment lengths
r =numpy.zeros_like(x)
r[1:] = numpy.cumsum(dr)                # integrate path
r_int = numpy.linspace(0, r.max(), 200) # regular spaced path
x_int = numpy.interp(r_int, r, x)       # integrate path
y_int = numpy.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [29]:
X = numpy.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = numpy.logical_and.reduce(numpy.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [30]:
X = numpy.random.rand(100)
N = 1000
idx = numpy.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = numpy.percentile(means, [2.5, 97.5])
print(confint)

[0.43588195 0.5472196 ]
